Splash screen and login UI implementation
NiharikaBalaga/rewarding-sale-app-flutter-app pull request #1
Opened 2024-01-29 19:14 UTC by PorkodiRajan

Added code for Splash screen and login UI

2024-01-29 21:13 UTC, jjacoboflorez95 approved these changes

2024-01-30 02:03 UTC, NiharikaBalaga approved these changes

2024-01-30 14:02 UTC, NiharikaBalaga requested changes
close and create new PR

2024-01-30 14:02 UTC, closed without merging

2024-01-30 14:03 UTC, NiharikaBalaga commented
wrong folder structure